### ISSUE TITLE
Numbers not being highlighted

### ISSUE THREAD

**Issue by fgaudo** [Corpauration/mdbook-treesitter#2]
Hey!

I was able to make this work with typescript, but i noticed that numbers are not being parsed and highlighted.

![image](https://github.com/Corpauration/mdbook-treesitter/assets/708636/de6e8c01-2511-470b-b12a-0a5168ac7380)

I'm not very skilled in Rust, but at first glance, it seems that the case for numbers is missing in `src/treesitter.rs` (number => hljs-number). Or is it something else?

Nice work btw!

**Comment by alyrow** [comment]
Thanks for the input! It was indeed that.
